/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    ", and as your energy tank begins to fill up, you will be able to begin upgrading your generator. There are four generators altogether, and after a while you will be able to improve all of them.": "，并且随着您的能量箱开始充满，您将能够开始升级您的发电机。总共有四个生成器，一段时间后您将能够改进所有这些生成器。",
    ". But just so that you know that I am aware of some of the basic requests and things to improve, here's an incomplete list of what I plan to address": ".但只是为了让您知道我知道一些基本要求和需要改进的地方，这是我计划解决的不完整列表",
    ". Once you've collected enough Antimatter, you will be able to warp, which will reset the game, but provide you with significant boosts to your generators, as well as unlocking new machines.": ".一旦你收集到足够的反物质，你就可以扭曲，这将重置游戏，但为你的发电机提供显着的提升，以及解锁新机器。",
    ". There are many varieties of incremental games, but the gist of it is having some sort of a production process, and then improving it - making it more efficient and more automated.": ".增量游戏有很多种，但其要点是拥有某种生产流程，然后对其进行改进——使其更高效、更自动化。",
    "3 is the lowest recommended value for your first warp. Holding out till 5 will allow you to buy Panel Upgrade I.": "3 是第一个经纱的最低推荐值。坚持到 5 将允许您购买面板升级 I。",
    "And don't worry about wasting your time on it: developing it will allow you to unlock the Magnetron fairly quickly, and Magnetron is your friend!": "不要担心在它上面浪费你的时间：开发它可以让你很快解锁磁控管，磁控管是你的朋友！",
    "And our intuitions about what's random are pretty bad. If you ask someone to provide a random string of 0s and 1s, they are more likely to write something like 100101101010001011, as opposed to 000000000010000000, although if the generation of individual digits is independent, both strings are equally as likely.": "我们对随机事件的直觉非常糟糕。如果您要求某人提供一个由 0 和 1 组成的随机字符串，他们更有可能写出类似 100101101010001011 的内容，而不是 000000000010000000，尽管如果单个数字的生成是独立的，则两个字符串的可能性相同。",
    "Oh yeah, and we'll get spaceships and venture into deep space!": "哦，是的，我们将获得宇宙飞船并冒险进入深空！",
    "Only a fool has no questions!": "只有傻子没有问题！",
    "our Discord": "我们的不和谐",
    "Provide somewhere the info for how much energy is required for the next power multiplier (x5 or x100": "在某处提供下一个功率倍增器（x5 或 x100）需要多少能量的信息",
    "Provide somewhere the info for how much energy is required for the next power multiplier (x5 or x100)": "在某处提供下一个功率倍增器（x5 或 x100）需要多少能量的信息",
    "Provide the ability to use several shuttles for collecting debris": "提供使用多个穿梭机收集碎片的能力",
    "Section for folks who have played previous versions of Machinery": "玩过以前版本的机械的人的部分",
    "Technical questions": "技术问题",
    "For instance, I have grand plans for Interdimensional Warp, and it is very probable that Quantum Numbers are going to be something different and will also be obtained in a completely different manner.": "例如，我对跨维度扭曲有宏伟的计划，量子数很可能会是不同的东西，也会以完全不同的方式获得。",
    "And, of course, I am also going to be working more on the existing machines. In other words, it's not only going to be about adding completely new content, but also tweaking, improving and enriching the already existing portions of the game. For example, I'd like to have way more warp upgrades. I'd like to have more missions. I'd like the Space Station to be doing something, and so on.": "当然，我还将在现有机器上进行更多工作。 换句话说，它不仅要添加全新的内容，还要调整、改进和丰富游戏中已有的部分。 例如，我想要更多的经线升级。 我希望有更多的任务。 我希望空间站能做点什么，等等。",
    "I get quite a lot of questions about the Magnetron. It might sometimes seem to have a mind of its own, as if it's sitting there, staring at you with its large button. But, in fact, it's a very basic piece of machinery that relies on a random number generator.": "我收到很多关于磁控管的问题。 它有时似乎有自己的想法，就好像它坐在那里，用它的大按钮盯着你。 但是，事实上，它是一个非常基本的机器，它依赖于随机数生成器。",
    "I have, in fact, implemented many of them. But not all! Mostly due to time constraints and the need to prioritize - I am but a single developer working in his free time. I did make sure to implement most pressing quality of life suggestions, and there are still quite a few on my list that I plan to work on in the future.": "事实上，我已经实现了其中的许多。 但不是所有的！ 主要是由于时间限制和需要确定优先级 - 我只是一个在空闲时间工作的开发人员。 我确实确保实施最紧迫的生活质量建议，而且我的清单上还有很多我计划在未来工作。",
    "The reason why Magnetron might seem less agreeable with time is because you are getting exposed to the whole range of its probability, which will include long periods of idle time. Additionally, Magnetron will become more necessary in later stages of the game, because a lot of your progress will have relied on Magnetron's boosts for many warps, making everything extra slow without it.": "磁控管似乎不太适合时间的原因是因为您接触到它的整个概率范围，其中包括长时间的空闲时间。 此外，在游戏的后期阶段，磁控管将变得更加必要，因为你的许多进步将依赖于磁控管对许多经线的提升，如果没有它，一切都会变得异常缓慢。",
    "Mathematically there's a reason for it - the button disappears when the cost of upgrading your generator becomes more expensive than buying the next generation. In fact, as soon as the new generation is available, it makes sense to simply buy it and not waste money on the remaining upgrades.": "从数学上讲，这是有原因的——当升级你的发电机的成本变得比购买下一代更贵时，这个按钮就会消失。 事实上，只要新一代面世，简单地购买它而不在剩余的升级上浪费金钱是有意义的。",
    "Nope! Machinery 0.99.1 is not compatible with any of the previous versions. Neither would you want it to be: it has way too many changes, including changes made to basic mechanics. If you would like to explore it, you would have to start anew, but I think you won't regret it!": "没有！ 机械装置 0.99.1 与之前的任何版本都不兼容。 你也不想这样：它有太多的变化，包括对基本机制的改变。 如果你想探索它，你必须重新开始，但我想你不会后悔的！",
    "In the game's universe it's a known issue with the Plasma generator that gives off low frequency rumble and that none of the engineers know how to fix. More context in the news ticker, but suffice to say, not anything you should worry about as a player ;": "在游戏的世界中，等离子发生器发出低频隆隆声是一个已知问题，并且没有工程师知道如何解决。 新闻代码中的更多背景信息，但足以说明，作为玩家，您无需担心任何事情；",
    "It turned out to be a pretty difficult problem when power upgrades are concerned, due to a couple of perculiarities of the mechanics of power upgrades. And I don't want to release the feature for every upgrade, but power. So, this is currently in the works.": "当涉及到电源升级时，事实证明这是一个相当困难的问题，因为电源升级机制有一些特殊之处。 而且我不想为每次升级发布该功能，而是发布电源。 所以，这目前正在进行中。",
    "The game is not meant to end here, and the decision to end at this point was because building a Space Station and becoming Chief Engineer sounds like a nice achievement, and I needed to start showing the game to players before committing to even more work.": "游戏并不意味着在这里结束，决定在这一点结束是因为建造空间站并成为总工程师听起来是一项不错的成就，我需要在投入更多工作之前开始向玩家展示游戏。",
    "Another important part of the game is": "游戏的另一个重要部分是",
    "Becoming Chief Engineer and continuing to collect Plasmic Frogs will make Magnetron more probable with time.": "成为总工程师并继续收集等离子青蛙将使磁​​控管随着时间的推移更有可能。",
    "Can I import my save from a previous version?": "我可以从以前的版本导入我的存档吗？",
    "Chrome seems to provide the most consistent performance.": "Chrome 似乎提供了最一致的性能。",
    "Do I need to \"develop my generators\" before switching to a new generation?": "在切换到新一代之前，我是否需要“开发我的发电机”？",
    "Do you lose your production bonus when you spend cubes?": "当你花费立方体时，你会失去你的生产奖金吗？",
    "Does the battery do anything?": "电池有什么作用吗？",
    "even when the tab was in focus": "即使标签处于焦点位置",
    "Frequently Asked Questions": "经常问的问题",
    "Future improvements": "未来的改进",
    "Gameplay questions": "游戏性问题",
    "How much antimatter should I aim for on my first run?": "我应该在第一次运行时瞄准多少反物质？",
    "How to play": "怎么玩",
    "I was upgrading my generator's power and suddenly its button disappeared!": "我正在升级发电机的电源，突然它的按钮消失了！",
    "I will at some point look into ways of solving this problem.": "我会在某个时候研究解决这个问题的方法。",
    "I am planning for more machines and, as hinted in the Quantum Numbers panel, there's even going to be a deeper level to this whole thing.": "我正在计划更多的机器，正如 量子数字 面板中所暗示的那样，整个事情甚至会有更深的层次。",
    "I click \"overdrive\", but it doesn't fill up my energy tank.": "我单击“过载”，但它并没有填满我的能量罐。",
    "I did receive truly awesome feedback and genuinely liked many ideas.": "我确实收到了非常棒的反馈，并且真的很喜欢很多想法。",
    "I have also tested the game on Chrome on an Android phone and it ran fine.": "我还在 Android 手机上的 Chrome 上测试了游戏，它运行良好。",
    "I have observed that at least in Chrome leaving sound on (even if at a very low level) forces the browser to run the tab normally. This is not a universal workaround, but it has helped many players.": "我观察到至少在 Chrome 中保持声音打开（即使在非常低的级别）会强制浏览器正常运行选项卡。这不是一个通用的解决方法，但它帮助了许多玩家。",
    "I have suggested feature X, you said you liked the idea, but it's not there": "我建议了功能 X，你说你喜欢这个想法，但它不存在",
    "I have tested the game on several laptops, running Linux and Windows. Both Firefox and Chrome performed fine on Linux systems. On Windows, Chrome ran the game normally but I have witnessed Firefox slowing it down": "我已经在几台运行 Linux 和 Windows 的笔记本电脑上测试了这款游戏。 Firefox 和 Chrome 在 Linux 系统上运行良好。在 Windows 上，Chrome 可以正常运行游戏，但我目睹了 Firefox 降低了它的速度",
    "I have unlocked the Orbital Telescope. Is this the end of the game?": "我已经解锁了轨道望远镜。这是游戏的结局吗？",
    "If both auto-upgrades are on, the funds will first be spent on Research Lab. You can also temporarily switch both off before triggering overdrive if you want to spend it on something else.": "如果两个自动升级都开启，资金将首先用于研究实验室。如果你想把它花在其他东西上，你也可以在触发过载之前暂时关闭它们。",
    "If you are coming from previous versions of Machinery, be sure to scroll down to read some important info on what's changed.": "如果您来自以前版本的机械，请务必向下滚动以阅读有关更改内容的一些重要信息。",
    "If you have ideas on how I can improve the game, feel free to reach out on": "如果您对我如何改进游戏有任何想法，请随时联系",
    "If you've never played such games, the idea might sound strange on paper. But it's a very accessible type of gaming, and many incremental games command audiences of millions of players. So, give it a try!": "如果您从未玩过此类游戏，那么这个想法在纸上可能听起来很奇怪。但它是一种非常容易获得的游戏类型，许多增量游戏拥有数百万玩家的受众。所以试试吧！",
    "In Machinery you start by clicking": "在机械中，您首先单击",
    "incremental game": "增量博弈",
    "It might be but I wouldn't count on it: it's not that it's difficult to make the saves compatible. It's that the game between versions is bound to change enough that your save won't make complete sense gameplay-wise.": "可能是这样，但我不会指望它：并不是很难使保存兼容。版本之间的游戏必然会发生足够的变化，以至于您的存档在游戏玩法方面不会完全有意义。",
    "Machinery [0.99.1]": "机械 [0.99.1]",
    "Machinery is an": "机械是一种",
    "Most subsequent machines will also provide bonuses to your generators. All of these machines will require a well developed Battery to function.": "大多数后续机器也会为您的发电机提供奖金。所有这些机器都需要一个开发良好的电池才能运行。",
    "My Magnetron sits idle for a really long time. Is it broken?": "我的磁控管闲置了很长时间。它坏了吗？",
    "The battery doesn't do anything for the generators. In fact, it drains their power. But it's an investment!": "电池对发电机没有任何作用。事实上，它耗尽了他们的力量。但这是一种投资！",
    "This could be because of the auto-upgrades: the Engineering Den and the Research Lab auto-buy. If any or both of these options are on, triggering overdrive will lead you to automatically spend the bonus.": "这可能是因为自动升级：Engineering Den 和 Research Lab 自动购买。如果这些选项中的任何一个或两个都打开，则触发超速驾驶将导致您自动花费奖金。",
    "This is a list of frequently asked questions. If you have a question that's not listed here, pop in to": "这是一个常见问题列表。如果您有未在此处列出的问题，请访问",
    "This is no longer necessary! If you see that a new generation is available, buy it - and all the multipliers will be set correctly.": "这不再是必要的！如果您看到有新一代可用，请购买 - 所有乘数都将正确设置。",
    "This means that the generator cannot be developed further and you should instead buy its new generation. I realize that this is a pretty awkward user experience, and I'll be thinking of ways to improve it.": "这意味着发电机无法进一步开发，您应该购买它的新一代。我意识到这是一种非常尴尬的用户体验，我会想办法改进它。",
    "Unfortunately, this is a known issue and many incremental games suffer from it. Vendors try to optimize browser performance and reducing the speed of code execution of tabs that are not in focus is one of the ways to get there.": "不幸的是，这是一个已知问题，许多增量游戏都深受其害。供应商尝试优化浏览器性能并降低未聚焦选项卡的代码执行速度是实现目标的方法之一。",
    "Unnamed Chief Engineer": "无名总工程师",
    "warping": "翘曲",
    "What's that occasional low rumble?": "什么是偶尔的低隆隆声？",
    "When switching to bulk buy (1/max), it would be good to show the price of bulk buy. Currently the price shown is only of the next upgrade": "当切换到批量购买（1/max）时，最好显示批量购买的价格。目前显示的价格仅为下一次升级的价格",
    "When the browser window and/or tab is out of focus, the game slows down": "当浏览器窗口和/或选项卡失焦时，游戏会变慢",
    "Which browser would you recommend for playing Machinery?": "你会推荐哪个浏览器来玩机械？",
    "Will the upcoming version of the game be compatible with my current save?": "即将推出的游戏版本会与我当前的存档兼容吗？",
    "Yes, this is the current end of the game. You obviously can continue playing, pushing those upgrades as far as you can and collecting all the 5 Quantum Numbers, as well as pushing the generators to generation X.": "是的，这是游戏的当前结局。你显然可以继续玩，尽可能地推动这些升级并收集所有 5 个量子数，并将生成器推到 X 代。",
    "You do not! Antimatter Amplifier bonus is completely independent of your antimatter cubes.": "你不！反物质放大器奖金完全独立于您的反物质立方体。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) \/ (.+) elves$/, '成本：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);