/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    "[auto]": "[自动]",
    "[30 sec]": "[30 秒]",
    "[Operator]": "[操作]",
    "Plasma": "等离子体",
    "Plasmic Frog": "等离子青蛙",
    "plastic flies live 30-50 minutes on average": "塑料苍蝇平均活 30-50 分钟",
    "Plastic Fly": "塑料飞",
    " limit": "上限",
    " limit auto-upgrade": "上限自动升级",
    " upgrades": "升级",
    "provides short boosts of efficiency to generators. It needs to be armed before it can be used. The probability of the Magnetron getting armed is 1 in 2000 for every request it receives.": "为发电机提供短暂的效率提升。它需要先武装起来才能使用。对于收到的每个请求，磁控管武装的概率是 2000 分之一。",
    "provides upgrades to generators. They are reset when you warp.": "提供对生成器的升级。当你变形时它们会被重置。",
    "Quantum Number ⌘": "量子数⌘",
    "Quantum Number is the resource required for the Interdimensional Warp. There are several achievements that will increment your Quantum Number": "量子数是跨维度扭曲所需的资源。有几项成就会增加你的量子数",
    "Rank": "级别",
    "Rank of Captain": "队长等级",
    "Rank of Chief Engineer": "总工程师职级",
    "Rank of Engineer": "工程师等级",
    "Rank of Floor Administrator": "楼层管理员等级",
    "reaching battery throughput of 35": "达到 35 的电池吞吐量",
    "reaching shuttle capacity of 300k": "达到 300k 的穿梭能力",
    "Reboot": "重启",
    "Recycle ⌬": "回收⌬",
    "Repair shuttle": "维修穿梭车",
    "Repopulation": "重新填充",
    "Requests to arm the Magnetron are being sent in the same cycle as the charging of the battery, therefore if the battery is not charging, the magnetron won't get armed. Therefore, the more generators are running, the more requests are being sent to the Magnetron.": "启动磁控管的请求与电池充电的周期相同，因此如果电池未充电，磁控管将不会启动。因此，运行的发电机越多，发送到磁控管的请求就越多。",
    "Research Lab": "研究实验室",
    "Reset game": "重置游戏",
    "Resolution": "解决",
    "Save and reload game for the setting to take effect": "保存并重新加载游戏以使设置生效",
    "Save now": "现在保存",
    "See prices without warping": "查看价格而不扭曲",
    "see whether the power upgrade has a x5 or a x100 multiplier": "查看电源升级是否有 x5 或 x100 乘数",
    "send spaceships on missions": "派遣宇宙飞船执行任务",
    "Setting it to 9% and lower will switch off the furnace, which will stop the production of components, and the furnace will begin to cool down.": "将其设置为 9% 或更低将关闭炉子，这将停止组件的生产，并且炉子将开始冷却。",
    "Setting it to a higher value will increase the speed at which the furnace heats up, but it won't affect how quickly the components are produced.": "将其设置为更高的值会增加熔炉加热的速度，但不会影响组件的生产速度。",
    "Shuttle": "穿梭",
    "Shuttle capacity": "穿梭能力",
    "shuttle capacity increases the amount of debris shuttles can carry": "穿梭机容量增加了穿梭机可以携带的碎片量",
    "Shuttlebay": "穿梭巴士湾",
    "Shuttles": "班车",
    "solo a generator that you want to track": "独奏您要跟踪的发生器",
    "Some upgrades will begin appearing only after certain machines are unlocked.": "某些升级只有在某些机器解锁后才会开始出现。",
    "Space Station": "空间站",
    "Stars cataloged": "分类的星星",
    "Start by clicking": "从点击开始",
    "Status": "状态",
    "Supply": "供应",
    "Supply limit": "供应上限",
    "Supply upgrades": "供应升级",
    "the foundry waste limit is decreased by 50 (reset at warp": "铸造废料限制减少 50（在扭曲时重置",
    "The Interdimensional Warp is going to be introduced in the upcoming versions of the game.": "跨维度扭曲将在即将推出的游戏版本中引入。",
    "The version of your save does not match the current version of the game. This might lead to incorrect behavior. Overwriting your save will hide this warning, but it is unlikely to fix the save.": "您保存的版本与游戏的当前版本不匹配。这可能会导致不正确的行为。覆盖您的保存将隐藏此警告，但不太可能修复保存。",
    "The waste management system provides a periodic bonus to your generators. You can reduce the amount of cycles required to trigger it by building shuttles and the Space Station.": "废物管理系统会定期为您的发电机提供奖励。您可以通过建造航天飞机和空间站来减少触发它所需的周期数量。",
    "to all generators' power": "所有发电机的功率",
    "Toggle scientific notation": "切换科学记数法",
    "Total amount of energy generated this run": "本次运行产生的总能量",
    "Unlock Battery": "解锁电池",
    "Unlock Foundry": "解锁铸造厂",
    "Unlock Magnetron": "解锁磁控管",
    "Unlock Mission Control": "解锁任务控制",
    "Unlock Orbital Telescope": "解锁轨道望远镜",
    "Unlock Space Station": "解锁空间站",
    "unlocks Engineering Den": "解锁工程巢穴",
    "unlocks Lifeforms Scanner": "解锁 Lifeforms 扫描仪",
    "unlocks Night Shift": "解锁夜班",
    "Volume": "体积",
    "Warp": "扭曲",
    "Warping right now will earn you": "现在扭曲会让你获得",
    "Waste": "浪费",
    "Welcome to": "欢迎来到",
    "Wipe save": "擦除保存",
    "Wiping your save will erase": "擦除您的保存将删除",
    "x2 Supply": "x2 供应",
    "You are an operator": "你是运营商",
    "you become Chief Engineer (permanent change": "你成为总工程师（永久变更",
    "Your save": "你的保存",
    "buying a Quantum Number warp upgrade": "购买量子数经线升级",
    "Cable Lizard": "电缆蜥蜴",
    "Cancel": "取消",
    "Charge limit": "充电上限",
    "Charge limit auto-upgrade": "充电刷新自动升级",
    "charting 2 galaxies": "绘制 2 个星系",
    "charts stars, galaxies and, in the future, habitable planets and interstellar lifeforms.": "绘制恒星、星系以及未来可居住行星和星际生命形式的图表。",
    "close": "关闭",
    "Close": "关闭",
    "Close Settings": "关闭设置",
    "Close Stats": "关闭统计",
    "collecting 100 duotronic butterflies": "收集 100 只双电子蝴蝶",
    "Collecting 100 increments your Quantum Number": "收集 100 个增量你的量子数",
    "Collecting lifeforms impacts their population. Warping when the Repopulation value is below 100% will lead to lifeforms becoming unavailable during the next warp. Growing Repopulation to 100% or higher at any of the subsequent warps will restore them.": "收集生命形式会影响他们的人口。当 Repopulation 值低于 100% 时进行扭曲将导致生命形式在下一次扭曲期间变得不可用。在随后的任何经线中将再生人口增加到 100% 或更高将恢复它们。",
    "Components": "成分",
    "Components per cycle": "每个周期的组件",
    "Construct Shuttlebay": "建造 Shuttlebay",
    "Control Panel": "控制面板",
    "copy to text file for backup": "复制到文本文件进行备份",
    "Deployment status: 0": "部署状态：0",
    "double the base supply unit up to 128": "将基本供应单元加倍，最多 128 个",
    "Duotronic Butterfly": "双电子蝴蝶",
    "Duration": "期间",
    "Electric": "电力",
    "Energy per Cycle": "每个周期的能量",
    "Engineering": "工程",
    "Engineering Den": "工程巢穴",
    "Engineering Den also provides Power limit and Charge limit auto-upgrades. Charge limit auto-upgrade is always ON.": "工程巢穴 还提供电源上限和充电上限自动升级。充电限制自动升级始终开启。",
    "Estimated Energy per Cycle": "每个周期的估计能量",
    "EU Parliament began working on replacing some of the outdated regulation regarding the rights of non-organics": "欧盟议会开始着手替换一些关于非有机物权利的过时法规",
    "Every 2 beetles increase the efficiency of the battery by 10": "每 2 只甲虫将电池效率提高 10",
    "Every 3 isopods increase Magnetron duration by 1 sec": "每 3 个等足动物增加磁控管持续时间 1 秒",
    "Every 5 worms increase Magnetron multiplier by 1": "每 5 条蠕虫增加 1 倍磁控管倍数",
    "Every fly increases the production of components by 5": "每飞一次，组件产量增加 5",
    "Every frog increases the probability of arming the Magnetron": "每只青蛙都会增加武装磁控管的概率",
    "Every lizard increases auxiliary power by 2": "每只蜥蜴增加 2 点辅助能量",
    "every shuttle built slightly decreases the foundry waste limit": "每建造一个梭子都会略微降低铸造废料的限制",
    "FAQ": "常问问题",
    "Foundry": "铸造厂",
    "Fun fact": "有趣的事实",
    "Galaxies charted": "星系图",
    "Game save": "游戏存档",
    "Generation II": "发电 II",
    "Generator": "发电机",
    "Generators": "发电机",
    "generators with no bonuses applied": "没有应用奖金的发电机",
    "Go Back": "返回",
    "Gravity": "重力",
    "Hint": "提示",
    "Import save": "导入保存",
    "In order to heat up and operate the furnace, the battery should be kept at 10% throughput.": "为了加热和操作熔炉，电池应保持在 10% 的吞吐量。",
    "increase the overall power output of all generators": "增加所有发电机的总功率输出",
    "Internal Bulletin": "内部公告",
    "is the gateway to deep space exploration.": "是深空探索的门户。",
    "is the power source for all the machines. Developing the battery allows to provide more power to the machines.": "是所有机器的动力源。开发电池可以为机器提供更多电力。",
    "Its furnace must be kept at a working temperature of 3000+ °C. If it cools down, it will stop producing components and would require re-heating.": "它的炉子必须保持在3000+°C的工作温度。如果冷却下来，它将停止生产组件并需要重新加热。",
    "Join our Discord": "加入我们的Discord",
    "Keep in mind that 1 in 2000 is a fairly low probability and that the process is truly random. It's quite normal to have very long periods of time with the Magnetron being dormant, and sometimes having it getting armed quickly several times in a row. You can increase this probability through collecting Plasmic Frogs.": "请记住，2000 年中有 1 次是相当低的概率，并且该过程是真正随机的。磁控管长时间处于休眠状态是很正常的，有时它会连续几次快速启动。你可以通过收集等离子蛙来增加这个概率。",
    "Let's go!": "我们走吧！",
    "Lifeform upgrades": "生命形式升级",
    "Lifeforms Scanner": "生命形式扫描仪",
    "lists and tracks the status of low orbit missions.": "列出并跟踪低轨道任务的状态。",
    "Louigi Verona": "路易吉·维罗纳",
    "Louigi Verona's Workshop": "路易吉·维罗纳的工作室",
    "Machinery": "机械",
    "Machines": "机器",
    "Magnetron": "磁控管",
    "Magnetron Alerting System": "磁控管警报系统",
    "Magnetron duration can now be upgraded to a maximum of 120 seconds": "磁控管持续时间现在可以升级到最长 120 秒",
    "Magnetron multiplier can now be upgraded to a maximum of x20": "磁控倍增器现在可以升级到最大 x20",
    "Magnetron Power": "磁控管电源",
    "Magnetron Resistance": "磁控管电阻",
    "manufactures components that will then be used to produce and maintain the space station, shuttle bay, probes and spaceships.": "制造用于生产和维护空间站、航天飞机舱、探测器和宇宙飞船的组件。",
    "Max Throughput": "最大吞吐量",
    "Mech Ciliate": "机械纤毛虫",
    "Mission Control": "任务控制",
    "Multiplier": "乘数",
    "Mutated Worm": "变异蠕虫",
    "Mute all": "全部静音",
    "Mute all audio": "静音所有音频",
    "Mute audio": "静音",
    "Mute Electric": "静音电动",
    "Mute generators": "静音发生器",
    "Mute Gravity": "静音重力",
    "Mute Nuclear": "静音核",
    "Mute Plasma": "静音等离子",
    "News": "消息",
    "Next save in": "下次保存还有",
    "Non-Organic Isopod": "非有机等足类动物",
    "Note that neither the Space Station, nor the Orbital Telescope can be deployed before the amount of low orbit debris is reduced to below 1000000000.": "请注意，在低轨道碎片数量减少到 1000000000 以下之前，空间站和轨道望远镜都无法部署。",
    "Nuclear": "核",
    "Nut Beetle": "坚果甲虫",
    "of your progress, including warp levels.": "你的进步，包括扭曲水平。",
    "Orbital Telescope": "轨道望远镜",
    "Original release date": "原始发布日期",
    "overdrive": "超速",
    ". Created by": ".由...制作",
    "\"I just work here\" - floor administrator": "“我只是在这里工作” - 楼层管理员",
    "\"Yangtzee Kiang\"": "“扬子江”",
    "> Deploy Orbital Telescope": "> 部署轨道望远镜",
    "> Deploy Space Station": "> 部署空间站",
    "> Remove low orbit debris": "> 清除低轨道碎片",
    "a key to another dimension": "另一个维度的钥匙",
    "A person on the Internet concludes that non-organic life is more normal than organic becase \"they don't poop\"": "网上有人断定非有机生活比有机生活更正常，因为“他们不拉屎”",
    "A UFO was spotted hovering over one of the generators. It was eaten by an unknown organism": "一个不明飞行物被发现在其中一个发电机上空盘旋。被不明生物吃掉了",
    "Academy": "研究院",
    "add non-organic lifeforms to the Lifeforms Scanner": "将非有机生命形式添加到生命形式扫描仪",
    "all": "全部",
    "All-time energy generated": "有史以来产生的能量",
    "allows you to align couplings. This improves the efficiency of the generators. Vibrations from the generators will constantly push the couplings out of alignment, so be sure to keep an eye on them!": "允许您对齐联轴器。这提高了发电机的效率。发电机的振动会不断地推动联轴器不对齐，所以一定要留意它们！",
    "allows you to build, repair and upgrade space shuttles.": "允许您建造、修理和升级航天飞机。",
    "allows you to identify the non-organic lifeforms that live in and around the generators. Each time you catch and identify one, it will provide permanent upgrades.": "允许您识别生活在发电机内部和周围的非有机生命形式。每次您捕获并识别一个时，它将提供永久升级。",
    "Amount till next antimatter": "直到下一个反物质的数量",
    "an audio alert is issued when the magnetron is armed": "磁控管布防时发出声音警报",
    "and see what happens!": "看看会发生什么！",
    "Announcement": "公告",
    "Antimatter": "反物质",
    "Antimatter amplifier": "反物质放大器",
    "Antimatter Amplifier": "反物质放大器",
    "Antimatter cubes": "反物质立方体",
    "Antimatter cubes in stock": "库存中的反物质立方体",
    "auto-buy Research Lab upgrades": "自动购买研究实验室升级",
    "Auxiliary power": "辅助电源",
    "Battery": "电池",
    "Battery charges from the generators. By specifying the percentage, you control the amount of power the battery consumes. If it's at 100%, it will consume all the energy produced by the generators.": "来自发电机的电池充电。通过指定百分比，您可以控制电池消耗的电量。如果达到 100%，它将消耗发电机产生的所有能量。",
    "becomes available when you reach a target amount of energy. The bonus fills up your whole energy tank, and after this the next target is set.": "当您达到目标能量时，即可使用。奖金会填满你的整个能量罐，然后设定下一个目标。",
    "Build shuttle": "建造穿梭车",
    "Building the Space Station has the following effects": "建造空间站有以下效果",
    "Building the Space Station has the following effects:": "建造空间站有以下效果：",
    "buy all available upgrades with a single click": "一键购买所有可用升级",
    "allow the clicking of the generators to guide your daily meditation": "让发生器的点击来指导您的日常冥想",
    "Mute All": "全部静音",
    "Overdrive": "过载",
    "/max]": "/最大]",
    "plastic flies use pipes and cables to travel between rooms": "塑料苍蝇使用管道和电缆在房间之间移动",
    "A group of civilians was sighted hiding under the Electric generator. Security has been informed about the incident.": "一群平民被发现躲在发电机下面。 安全部门已被告知该事件。",
    "iridium fleas are illegal to trade and keep as pets": "铱跳蚤作为宠物交易和饲养是非法的",
    "Save successfully imported. Reload page.": "存档成功导入。 请刷新，重新加载页面。",
    "acid pool party is happening": "酸池派对正在举行",
    "a floor administrator is attacked by a couple of plasmic frogs": "一名楼层管理员被几只等离子青蛙袭击",
    "A non-organics flea market will be held Saturday afternoon, as usual. Iridium fleas are still banned.": "像往常一样，周六下午将举行一个非有机跳蚤市场。 铱跳蚤仍然被禁止。",
    "A scientist alleges that non-organic isopods are an evolved lifeform": "一位科学家声称非有机等足类动物是一种进化的生命形式",
    "antimatter storage has a shape of a large egg?": "反物质储存有一个大鸡蛋的形状？",
    "Did you know that": "你知道吗",
    "EU Parliament has just announced that engineers are going to be honored every Wednesday": "欧盟议会刚刚宣布，工程师将在每周三获得荣誉",
    "operator": "操作",
    "tracks of mutated worms were spotted on the wall of the Plasma generator": "等离子发生器的墙上发现了变异蠕虫的踪迹",
    "You are an": "你是一个",
    "minimum x2 for any effect": "最小 x2 任何效果",
    "a floor administrator witnessedthe mating of cable lizards. Counseling sessions have been set up": "一位楼层管理员目睹了电缆蜥蜴的交配。 已设立辅导班",
    "Be careful when attempting to debug the low-frequency hum of the Plasma generator so as not to be kidnapped by a nanobot tribe": "尝试调试等离子发生器的低频嗡嗡声时要小心，以免被纳米机器人部落绑架",
    "each mech ciliate has a unique signature, which is facilitating their rise as currency": "每个机械纤毛虫都有一个独特的签名，这促进了它们作为货币的崛起",
    "EU Parliament considers setting up a committee dedicated to studying non-organic isopods as a potential food source": "欧盟议会考虑成立一个委员会，专门研究非有机等足类动物作为潜在的食物来源",
    "Several items disappeared from the Research Lab. Security was informed": "几件物品从研究实验室消失了。 保安被告知",
    "Someone online concludes that the low-frequency hum of the Plasma generator is a sign of emerging intelligence": "网上有人断定等离子发生器的低频嗡嗡声是新兴智能的标志",
    "Warning": "警告",
    "\"I know, right?\" - intern": "“我知道，对吧？”——实习生",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "January 2022": "2022 年 1 月",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    "Machinery [0.99.1]": "机械师 [0.99.1]",
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Panel Upgrade ": "面板升级 ",
    "Quantity: ": "数量：",
    "Power": "电源",
    "Debris detected:": "检测到碎片：",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    " warp levels": " 扭曲等级",
    "% Power": "% 电源",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^⌬([\d\.]+)$/,
    /^⌬([\d\.]+)k$/,
    /^⌬([\d\.]+)M$/,
    /^⌬([\d\.]+)S$/,
    /^⌬([\d\.]+)Q$/,
    /^⌬([\d\.]+)T$/,
    /^⌬([\d\.]+)k\/⌬([\d\.]+)M$/,
    /^⌬([\d\.]+)k\/⌬([\d\.]+)k$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.,]+) Shuttle$/, '$1 穿梭'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) \/ (.+) elves$/, '成本：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);