/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    "[auto]": "[自动]",
    "[30 sec]": "[30 秒]",
    "[Operator]": "[操作]",
    "Plasma": "等离子体",
    "Plasmic Frog": "等离子青蛙",
    "plastic flies live 30-50 minutes on average": "塑料苍蝇平均活 30-50 分钟",
    "Plastic Fly": "塑料飞",
    " limit": "上限",
    " limit auto-upgrade": "上限自动升级",
    " upgrades": "升级",
    "provides short boosts of efficiency to generators. It needs to be armed before it can be used. The probability of the Magnetron getting armed is 1 in 2000 for every request it receives.": "为发电机提供短暂的效率提升。它需要先武装起来才能使用。对于收到的每个请求，磁控管武装的概率是 2000 分之一。",
    "provides upgrades to generators. They are reset when you warp.": "提供对生成器的升级。当你变形时它们会被重置。",
    "Quantum Number ⌘": "量子数⌘",
    "Quantum Number is the resource required for the Interdimensional Warp. There are several achievements that will increment your Quantum Number": "量子数是跨维度扭曲所需的资源。有几项成就会增加你的量子数",
    "Rank": "级别",
    "Rank of Captain": "队长等级",
    "Rank of Chief Engineer": "总工程师职级",
    "Rank of Engineer": "工程师等级",
    "Rank of Floor Administrator": "楼层管理员等级",
    "reaching battery throughput of 35": "达到 35 的电池吞吐量",
    "reaching shuttle capacity of 300k": "达到 300k 的穿梭能力",
    "Reboot": "重启",
    "Recycle ⌬": "回收⌬",
    "Repair shuttle": "维修穿梭车",
    "Repopulation": "重新填充",
    "Requests to arm the Magnetron are being sent in the same cycle as the charging of the battery, therefore if the battery is not charging, the magnetron won't get armed. Therefore, the more generators are running, the more requests are being sent to the Magnetron.": "启动磁控管的请求与电池充电的周期相同，因此如果电池未充电，磁控管将不会启动。因此，运行的发电机越多，发送到磁控管的请求就越多。",
    "Research Lab": "研究实验室",
    "Reset game": "重置游戏",
    "Resolution": "解决",
    "Save and reload game for the setting to take effect": "保存并重新加载游戏以使设置生效",
    "Save now": "现在保存",
    "See prices without warping": "查看价格而不扭曲",
    "see whether the power upgrade has a x5 or a x100 multiplier": "查看电源升级是否有 x5 或 x100 乘数",
    "send spaceships on missions": "派遣宇宙飞船执行任务",
    "Setting it to 9% and lower will switch off the furnace, which will stop the production of components, and the furnace will begin to cool down.": "将其设置为 9% 或更低将关闭炉子，这将停止组件的生产，并且炉子将开始冷却。",
    "Setting it to a higher value will increase the speed at which the furnace heats up, but it won't affect how quickly the components are produced.": "将其设置为更高的值会增加熔炉加热的速度，但不会影响组件的生产速度。",
    "Shuttle": "穿梭",
    "Shuttle capacity": "穿梭能力",
    "shuttle capacity increases the amount of debris shuttles can carry": "穿梭机容量增加了穿梭机可以携带的碎片量",
    "Shuttlebay": "穿梭巴士湾",
    "Shuttles": "班车",
    "solo a generator that you want to track": "独奏您要跟踪的发生器",
    "Some upgrades will begin appearing only after certain machines are unlocked.": "某些升级只有在某些机器解锁后才会开始出现。",
    "Space Station": "空间站",
    "Stars cataloged": "分类的星星",
    "Start by clicking": "从点击开始",
    "Status": "状态",
    "Supply": "供应",
    "Supply limit": "供应上限",
    "Supply upgrades": "供应升级",
    "the foundry waste limit is decreased by 50 (reset at warp": "铸造废料限制减少 50（在扭曲时重置",
    "The Interdimensional Warp is going to be introduced in the upcoming versions of the game.": "跨维度扭曲将在即将推出的游戏版本中引入。",
    "The version of your save does not match the current version of the game. This might lead to incorrect behavior. Overwriting your save will hide this warning, but it is unlikely to fix the save.": "您保存的版本与游戏的当前版本不匹配。这可能会导致不正确的行为。覆盖您的保存将隐藏此警告，但不太可能修复保存。",
    "The waste management system provides a periodic bonus to your generators. You can reduce the amount of cycles required to trigger it by building shuttles and the Space Station.": "废物管理系统会定期为您的发电机提供奖励。您可以通过建造航天飞机和空间站来减少触发它所需的周期数量。",
    "to all generators' power": "所有发电机的功率",
    "Toggle scientific notation": "切换科学记数法",
    "Total amount of energy generated this run": "本次运行产生的总能量",
    "Unlock Battery": "解锁电池",
    "Unlock Foundry": "解锁铸造厂",
    "Unlock Magnetron": "解锁磁控管",
    "Unlock Mission Control": "解锁任务控制",
    "Unlock Orbital Telescope": "解锁轨道望远镜",
    "Unlock Space Station": "解锁空间站",
    "unlocks Engineering Den": "解锁工程巢穴",
    "unlocks Lifeforms Scanner": "解锁 Lifeforms 扫描仪",
    "unlocks Night Shift": "解锁夜班",
    "Volume": "体积",
    "Warp": "扭曲",
    "Warping right now will earn you": "现在扭曲会让你获得",
    "Waste": "浪费",
    "Welcome to": "欢迎来到",
    "Wipe save": "擦除保存",
    "Wiping your save will erase": "擦除您的保存将删除",
    "x2 Supply": "x2 供应",
    "You are an operator": "你是运营商",
    "you become Chief Engineer (permanent change": "你成为总工程师（永久变更",
    "Your save": "你的保存",
    "buying a Quantum Number warp upgrade": "购买量子数经线升级",
    "Cable Lizard": "电缆蜥蜴",
    "Cancel": "取消",
    "Charge limit": "充电上限",
    "Charge limit auto-upgrade": "充电刷新自动升级",
    "charting 2 galaxies": "绘制 2 个星系",
    "charts stars, galaxies and, in the future, habitable planets and interstellar lifeforms.": "绘制恒星、星系以及未来可居住行星和星际生命形式的图表。",
    "close": "关闭",
    "Close": "关闭",
    "Close Settings": "关闭设置",
    "Close Stats": "关闭统计",
    "collecting 100 duotronic butterflies": "收集 100 只双电子蝴蝶",
    "Collecting 100 increments your Quantum Number": "收集 100 个增量你的量子数",
    "Collecting lifeforms impacts their population. Warping when the Repopulation value is below 100% will lead to lifeforms becoming unavailable during the next warp. Growing Repopulation to 100% or higher at any of the subsequent warps will restore them.": "收集生命形式会影响他们的人口。当 Repopulation 值低于 100% 时进行扭曲将导致生命形式在下一次扭曲期间变得不可用。在随后的任何经线中将再生人口增加到 100% 或更高将恢复它们。",
    "Components": "成分",
    "Components per cycle": "每个周期的组件",
    "Construct Shuttlebay": "建造 Shuttlebay",
    "Control Panel": "控制面板",
    "copy to text file for backup": "复制到文本文件进行备份",
    "Deployment status: 0": "部署状态：0",
    "double the base supply unit up to 128": "将基本供应单元加倍，最多 128 个",
    "Duotronic Butterfly": "双电子蝴蝶",
    "Duration": "期间",
    "Electric": "电力",
    "Energy per Cycle": "每个周期的能量",
    "Engineering": "工程",
    "Engineering Den": "工程巢穴",
    "Engineering Den also provides Power limit and Charge limit auto-upgrades. Charge limit auto-upgrade is always ON.": "工程巢穴 还提供电源上限和充电上限自动升级。充电限制自动升级始终开启。",
    "Estimated Energy per Cycle": "每个周期的估计能量",
    "EU Parliament began working on replacing some of the outdated regulation regarding the rights of non-organics": "欧盟议会开始着手替换一些关于非有机物权利的过时法规",
    "Every 2 beetles increase the efficiency of the battery by 10": "每 2 只甲虫将电池效率提高 10",
    "Every 3 isopods increase Magnetron duration by 1 sec": "每 3 个等足动物增加磁控管持续时间 1 秒",
    "Every 5 worms increase Magnetron multiplier by 1": "每 5 条蠕虫增加 1 倍磁控管倍数",
    "Every fly increases the production of components by 5": "每飞一次，组件产量增加 5",
    "Every frog increases the probability of arming the Magnetron": "每只青蛙都会增加武装磁控管的概率",
    "Every lizard increases auxiliary power by 2": "每只蜥蜴增加 2 点辅助能量",
    "every shuttle built slightly decreases the foundry waste limit": "每建造一个梭子都会略微降低铸造废料的限制",
    "FAQ": "常问问题",
    "Foundry": "铸造厂",
    "Fun fact": "有趣的事实",
    "Galaxies charted": "星系图",
    "Game save": "游戏存档",
    "Generation II": "发电 II",
    "Generator": "发电机",
    "Generators": "发电机",
    "generators with no bonuses applied": "没有应用奖金的发电机",
    "Go Back": "返回",
    "Gravity": "重力",
    "Hint": "提示",
    "Import save": "导入保存",
    "In order to heat up and operate the furnace, the battery should be kept at 10% throughput.": "为了加热和操作熔炉，电池应保持在 10% 的吞吐量。",
    "increase the overall power output of all generators": "增加所有发电机的总功率输出",
    "Internal Bulletin": "内部公告",
    "is the gateway to deep space exploration.": "是深空探索的门户。",
    "is the power source for all the machines. Developing the battery allows to provide more power to the machines.": "是所有机器的动力源。开发电池可以为机器提供更多电力。",
    "Its furnace must be kept at a working temperature of 3000+ °C. If it cools down, it will stop producing components and would require re-heating.": "它的炉子必须保持在3000+°C的工作温度。如果冷却下来，它将停止生产组件并需要重新加热。",
    "Join our Discord": "加入我们的Discord",
    "Keep in mind that 1 in 2000 is a fairly low probability and that the process is truly random. It's quite normal to have very long periods of time with the Magnetron being dormant, and sometimes having it getting armed quickly several times in a row. You can increase this probability through collecting Plasmic Frogs.": "请记住，2000 年中有 1 次是相当低的概率，并且该过程是真正随机的。磁控管长时间处于休眠状态是很正常的，有时它会连续几次快速启动。你可以通过收集等离子蛙来增加这个概率。",
    "Let's go!": "我们走吧！",
    "Lifeform upgrades": "生命形式升级",
    "Lifeforms Scanner": "生命形式扫描仪",
    "lists and tracks the status of low orbit missions.": "列出并跟踪低轨道任务的状态。",
    "Louigi Verona": "路易吉·维罗纳",
    "Louigi Verona's Workshop": "路易吉·维罗纳的工作室",
    "Machinery": "机械",
    "Machines": "机器",
    "Magnetron": "磁控管",
    "Magnetron Alerting System": "磁控管警报系统",
    "Magnetron duration can now be upgraded to a maximum of 120 seconds": "磁控管持续时间现在可以升级到最长 120 秒",
    "Magnetron multiplier can now be upgraded to a maximum of x20": "磁控倍增器现在可以升级到最大 x20",
    "Magnetron Power": "磁控管电源",
    "Magnetron Resistance": "磁控管电阻",
    "manufactures components that will then be used to produce and maintain the space station, shuttle bay, probes and spaceships.": "制造用于生产和维护空间站、航天飞机舱、探测器和宇宙飞船的组件。",
    "Max Throughput": "最大吞吐量",
    "Mech Ciliate": "机械纤毛虫",
    "Mission Control": "任务控制",
    "Multiplier": "乘数",
    "Mutated Worm": "变异蠕虫",
    "Mute all": "全部静音",
    "Mute all audio": "静音所有音频",
    "Mute audio": "静音",
    "Mute Electric": "静音电动",
    "Mute generators": "静音发生器",
    "Mute Gravity": "静音重力",
    "Mute Nuclear": "静音核",
    "Mute Plasma": "静音等离子",
    "News": "消息",
    "Next save in": "下次保存还有",
    "Non-Organic Isopod": "非有机等足类动物",
    "Note that neither the Space Station, nor the Orbital Telescope can be deployed before the amount of low orbit debris is reduced to below 1000000000.": "请注意，在低轨道碎片数量减少到 1000000000 以下之前，空间站和轨道望远镜都无法部署。",
    "Nuclear": "核",
    "Nut Beetle": "坚果甲虫",
    "of your progress, including warp levels.": "你的进步，包括扭曲水平。",
    "Orbital Telescope": "轨道望远镜",
    "Original release date": "原始发布日期",
    "overdrive": "超速",
    ". Created by": ".由...制作",
    "\"I just work here\" - floor administrator": "“我只是在这里工作” - 楼层管理员",
    "\"Yangtzee Kiang\"": "“扬子江”",
    "> Deploy Orbital Telescope": "> 部署轨道望远镜",
    "> Deploy Space Station": "> 部署空间站",
    "> Remove low orbit debris": "> 清除低轨道碎片",
    "a key to another dimension": "另一个维度的钥匙",
    "A person on the Internet concludes that non-organic life is more normal than organic becase \"they don't poop\"": "网上有人断定非有机生活比有机生活更正常，因为“他们不拉屎”",
    "A UFO was spotted hovering over one of the generators. It was eaten by an unknown organism": "一个不明飞行物被发现在其中一个发电机上空盘旋。被不明生物吃掉了",
    "Academy": "研究院",
    "add non-organic lifeforms to the Lifeforms Scanner": "将非有机生命形式添加到生命形式扫描仪",
    "all": "全部",
    "All-time energy generated": "有史以来产生的能量",
    "allows you to align couplings. This improves the efficiency of the generators. Vibrations from the generators will constantly push the couplings out of alignment, so be sure to keep an eye on them!": "允许您对齐联轴器。这提高了发电机的效率。发电机的振动会不断地推动联轴器不对齐，所以一定要留意它们！",
    "allows you to build, repair and upgrade space shuttles.": "允许您建造、修理和升级航天飞机。",
    "allows you to identify the non-organic lifeforms that live in and around the generators. Each time you catch and identify one, it will provide permanent upgrades.": "允许您识别生活在发电机内部和周围的非有机生命形式。每次您捕获并识别一个时，它将提供永久升级。",
    "Amount till next antimatter": "直到下一个反物质的数量",
    "an audio alert is issued when the magnetron is armed": "磁控管布防时发出声音警报",
    "and see what happens!": "看看会发生什么！",
    "Announcement": "公告",
    "Antimatter": "反物质",
    "Antimatter amplifier": "反物质放大器",
    "Antimatter Amplifier": "反物质放大器",
    "Antimatter cubes": "反物质立方体",
    "Antimatter cubes in stock": "库存中的反物质立方体",
    "auto-buy Research Lab upgrades": "自动购买研究实验室升级",
    "Auxiliary power": "辅助电源",
    "Battery": "电池",
    "Battery charges from the generators. By specifying the percentage, you control the amount of power the battery consumes. If it's at 100%, it will consume all the energy produced by the generators.": "来自发电机的电池充电。通过指定百分比，您可以控制电池消耗的电量。如果达到 100%，它将消耗发电机产生的所有能量。",
    "becomes available when you reach a target amount of energy. The bonus fills up your whole energy tank, and after this the next target is set.": "当您达到目标能量时，即可使用。奖金会填满你的整个能量罐，然后设定下一个目标。",
    "Build shuttle": "建造穿梭车",
    "Building the Space Station has the following effects": "建造空间站有以下效果",
    "Building the Space Station has the following effects:": "建造空间站有以下效果：",
    "buy all available upgrades with a single click": "一键购买所有可用升级",
    "allow the clicking of the generators to guide your daily meditation": "让发生器的点击来指导您的日常冥想",
    "Mute All": "全部静音",
    "Overdrive": "过载",
    "/max]": "/最大]",
    "plastic flies use pipes and cables to travel between rooms": "塑料苍蝇使用管道和电缆在房间之间移动",
    "A group of civilians was sighted hiding under the Electric generator. Security has been informed about the incident.": "一群平民被发现躲在发电机下面。 安全部门已被告知该事件。",
    "iridium fleas are illegal to trade and keep as pets": "铱跳蚤作为宠物交易和饲养是非法的",
    "Save successfully imported. Reload page.": "存档成功导入。 请刷新，重新加载页面。",
    "acid pool party is happening": "酸池派对正在举行",
    "a floor administrator is attacked by a couple of plasmic frogs": "一名楼层管理员被几只等离子青蛙袭击",
    "A non-organics flea market will be held Saturday afternoon, as usual. Iridium fleas are still banned.": "像往常一样，周六下午将举行一个非有机跳蚤市场。 铱跳蚤仍然被禁止。",
    "A scientist alleges that non-organic isopods are an evolved lifeform": "一位科学家声称非有机等足类动物是一种进化的生命形式",
    "antimatter storage has a shape of a large egg?": "反物质储存有一个大鸡蛋的形状？",
    "Did you know that": "你知道吗",
    "EU Parliament has just announced that engineers are going to be honored every Wednesday": "欧盟议会刚刚宣布，工程师将在每周三获得荣誉",
    "operator": "操作",
    "tracks of mutated worms were spotted on the wall of the Plasma generator": "等离子发生器的墙上发现了变异蠕虫的踪迹",
    "You are an": "你是一个",
    "minimum x2 for any effect": "最小 x2 任何效果",
    "a floor administrator witnessedthe mating of cable lizards. Counseling sessions have been set up": "一位楼层管理员目睹了电缆蜥蜴的交配。 已设立辅导班",
    "Be careful when attempting to debug the low-frequency hum of the Plasma generator so as not to be kidnapped by a nanobot tribe": "尝试调试等离子发生器的低频嗡嗡声时要小心，以免被纳米机器人部落绑架",
    "each mech ciliate has a unique signature, which is facilitating their rise as currency": "每个机械纤毛虫都有一个独特的签名，这促进了它们作为货币的崛起",
    "EU Parliament considers setting up a committee dedicated to studying non-organic isopods as a potential food source": "欧盟议会考虑成立一个委员会，专门研究非有机等足类动物作为潜在的食物来源",
    "Several items disappeared from the Research Lab. Security was informed": "几件物品从研究实验室消失了。 保安被告知",
    "Someone online concludes that the low-frequency hum of the Plasma generator is a sign of emerging intelligence": "网上有人断定等离子发生器的低频嗡嗡声是新兴智能的标志",
    "Warning": "警告",
    "\"I know, right?\" - intern": "“我知道，对吧？”——实习生",
    "a bakery began accepting mech ciliates as currency": "一家面包店开始接受机械纤毛虫作为货币",
    "A conspiracy theorist alleges that unseen spiders meet the definition of a veridical paradox": "一位阴谋论者声称看不见的蜘蛛符合真实悖论的定义",
    "a crowding of cable lizards has created significant clutter in the Eingineering Den. Please clear it out. Thank you.": "拥挤的电缆蜥蜴在工程巢穴中造成了严重的混乱。请清除它。谢谢你。",
    "a duotronic butterfly decorated with edible elements was sold for a record sum of money": "一只装饰有可食用元素的双电子蝴蝶以创纪录的价格售出",
    "a duotronic butterfly decorated with edible elements was sold for an undisclosed sum of money": "一只装饰有可食用元素的双电子蝴蝶以未公开的金额出售",
    "a duotronic butterfly infused with gold was sold for a record sum of money": "一只注入黄金的双电子蝴蝶以创纪录的价格售出",
    "a floor administrator witnessedskin shedding of non-organic isopods. Counseling sessions have been set up": "一位楼层管理员目睹了非有机等足类动物的皮肤脱落。已设立辅导班",
    "A group of unidentified organisms was sighted hiding under the Magnetron. Security has been informed about the incident.": "一群身份不明的生物被发现藏在磁控管下。安全部门已被告知该事件。",
    "A local comedian believes that non-organic isopods are an evolved lifeform": "一位当地喜剧演员认为非有机等足类动物是一种进化的生命形式",
    "A local comedian concludes that non-organic life should be considered property theft: \"They incorporate our stuff into their bodies and then run away\"": "一位当地喜剧演员得出结论，非有机生命应被视为财产盗窃：“他们将我们的东西融入他们的身体，然后逃跑”",
    "A local comedian insists that duotronic butterflies are actually monotronic": "一位当地喜剧演员坚持认为双电子蝴蝶实际上是单电子的",
    "A local comedian suggests that unseen spiders actually exist": "一位当地喜剧演员暗示实际上存在看不见的蜘蛛",
    "a local confectionery began accepting mech ciliates as currency": "当地一家糖果店开始接受机械纤毛虫作为货币",
    "a non-organic isopod painted in rainbow colors was confiscated by authorities": "当局没收了一只涂有彩虹色的非有机等足类动物",
    "a nut beetle decorated with edible elements was sold for an undisclosed sum of money": "以可食用元素装饰的坚果甲虫以未公开的金额出售",
    "a nut beetle infused with gold was sold for an undisclosed sum of money": "一只注入黄金的坚果甲虫以未公开的金额出售",
    "a nut beetle painted in rainbow colors was traded for a cup of coffee": "一只涂成彩虹色的坚果甲虫被换成了一杯咖啡",
    "A person on the Internet concludes that duotronic butterflies are actually monotronic": "网上有人断定双电子蝴蝶其实是单电子的",
    "a pipe burst in section 4, please put on your radiation shielding suit when passing through. Thank you": "第 4 段有管道爆裂，通过时请穿上防辐射服。谢谢",
    "A prominent writer concludes that unseen spiders meet the definition of a veridical paradox": "一位著名作家得出结论，看不见的蜘蛛符合真实悖论的定义",
    "A prominent writer wonders if plastic flies cannot be killed with a plastic flyswatter": "一位著名作家想知道塑料苍蝇是否不能用塑料苍蝇拍杀死",
    "A referendum voices support for more research into unkempt engineers that have been spotted throughout the city": "全民投票支持对整个城市发现的蓬头垢面的工程师进行更多研究",
    "A study finds no health risks of frequent warping": "一项研究发现频繁翘曲没有健康风险",
    "A study reveals that most people consider engineers to be true artists": "一项研究表明，大多数人认为工程师是真正的艺术家",
    "A study reveals that non-organic organisms have been spotted in major cities across the world": "一项研究表明，在世界各地的主要城市都发现了非有机生物",
    "A study reveals that people who warp frequently experience warping more frequently": "一项研究表明，经常翘曲的人更频繁地经历翘曲",
    "An amateur philosopher alleges that Pek Monster is an amalgamation of all the known non-organic lifeforms": "一位业余哲学家声称 Pek Monster 是所有已知非有机生命形式的融合",
    "An amateur philosopher insists that non-organic life is more normal than organic becase \"they don't poop\"": "一位业余哲学家坚持认为非有机生命比有机生命更正常，因为“它们不会拉屎”",
    "An amateur philosopher maintains that duotronic butterflies are actually monotronic": "一位业余哲学家认为双电子蝴蝶实际上是单电子的",
    "an unclear event occured in section 6, please keep out until the investigation is concluded. Thank you": "第6节发生不明事件，请在调查结束前保持警惕。谢谢",
    "An unidentified crawling object (UCO) was spotted devouring what appeared to have been a basketball": "发现一个身份不明的爬行物体 (UCO) 吞噬了一个看似篮球的东西",
    "An unidentified crawling object (UCO) was spotted in the Engineering Den": "在工程中心发现了一个不明爬行物体 (UCO)",
    "An unofficial non-organics collectors' convention is going to be held next month": "下个月将举行一次非官方的非有机物收藏家大会",
    "Be careful when attempting to debug the low-frequency hum of the Plasma generator so as not to be eaten by an unknown organism": "尝试调试等离子发生器的低频嗡嗡声时要小心，以免被未知生物吃掉",
    "Be extra careful when attempting to catch a non-organic isopod so as not to be kidnapped by a nanobot tribe": "尝试捕捉非有机等足类动物时要格外小心，以免被纳米机器人部落绑架",
    "Be extra careful when attempting to manually align couplings so as not to be kidnapped by a nanobot tribe": "尝试手动对齐联轴器时要格外小心，以免被纳米机器人部落绑架",
    "breakfast is happening": "早餐正在发生",
    "Chief Engineers have designated living quarters on the Space Station?": "总工程师在空间站有指定的居住区吗？",
    "don't worry too much about the Repopulation parameter. It might stay at 0% for a long time, but will then grow very quickly": "不要太担心 Repopulation 参数。它可能会在很长一段时间内保持在 0%，但随后会迅速增长",
    "each mech ciliate has a unique signature, which is why they are being used as currency": "每个机械纤毛虫都有一个独特的签名，这就是为什么它们被用作货币",
    "EU Parliament began a session on replacing some of the outdated regulation regarding the rights of non-organics": "欧盟议会开始召开会议，讨论更换一些关于非有机物权利的过时法规",
    "EU Parliament was grilled by the press regarding the invasion of relatively large worms": "欧盟议会因相对较大的蠕虫入侵而被媒体质问",
    "Factory kitchen is situated right next to the Nuclear generator and relies on it for heating and power?": "工厂厨房就在核电站旁边，依靠它来供暖和供电？",
    "floor administrators have set up guard posts to protect the Magnetron from mutated worms invasions": "楼层管理员设置了岗哨以保护磁控管免受变异蠕虫的入侵",
    "floor administrators have set up guard posts to ward off cable lizards": "楼层管理员已设置岗哨以抵御电缆蜥蜴",
    "Foundry's waste management system is its own chemical plant in a separate building?": "Foundry的废物管理系统是自己的化工厂在一个单独的大楼里吗？",
    "Local News": "本地新闻",
    "Low-frequency noises from below the Plasma generator were shown to be a direct consequence of irresponsible engineering experiments": "来自等离子发生器下方的低频噪声被证明是不负责任的工程​​实验的直接后果",
    "Machinery is less likely to slow down when out of focus on some browsers if you leave the sound on. You can make it really quiet": "如果您让声音保持打开状态，当您对某些浏览器失去关注时，机器速度不太可能变慢。你可以让它变得非常安静",
    "Mech ciliate trader jailed for fraud": "机械纤毛虫贸易商因欺诈被判入狱",
    "lunch is happening": "午餐正在发生",
    "Mech ciliate trader makes a fortune": "机械纤毛虫商人发了财",
    "Mech ciliate trader sells socks to buy more ciliates": "机械纤毛虫贸易商出售袜子以购买更多纤毛虫",
    "mech ciliates can now be found in every device of both the Power Plant and Factory": "机械纤毛虫现在可以在发电厂和工厂的每个设备中找到",
    "Mission Control is built entirely out of recycled android brains?": "Mission Control 完全是用回收的 android 大脑构建的？",
    "Non-organic eggs of unknown insect species  were discovered on one of the pipes of the Electric generator. Scientists ponder if there is any risk to the engineers in the area": "在发电机的一根管道上发现了未知昆虫种类的无机卵。科学家们思考该地区的工程师是否有任何风险",
    "non-organic isopods eat mazut, which is why they have to be kept out of fuel storage compartments": "非有机等足类动物吃mazut，这就是为什么它们必须远离燃料储藏室",
    "plasmic frogs are actually dangerous to humans and can inflict damage by shooting streams of plasma": "等离子青蛙实际上对人类很危险，可以通过射出等离子流来造成伤害",
    "Plasmic frogs were shown to be a direct consequence of the second law of thermodynamics": "等离子蛙被证明是热力学第二定律的直接结果",
    "Please report any unidentified persons with unkempt appearances unless you suspect they are engineers": "除非您怀疑他们是工程师，否则请报告任何外表蓬乱的身份不明的人",
    "Screwdriver throwing contest will be held in the Engineering Den at 1800": "螺丝刀投掷比赛将于 1800 年在 工程巢穴 举行",
    "section 10 is closed for maintenance": "第 10 区因维修而关闭",
    "Several interns got lost in the Engineering Den last week": "上周有几个实习生在工程中心迷路了",
    "Several items disappeared from the Research Lab. Nut beetles are suspected": "几件物品从研究实验室消失了。怀疑是坚果甲虫",
    "Several visitors got lost in the Engineering Den last week": "上周有几位游客在工程中心迷路了",
    "Someone online believes that non-organic isopods are secretly organic": "网上有人认为非有机等足类动物暗中有机",
    "Talk show host claims that unseen spiders actually exist": "脱口秀主持人声称实际上存在看不见的蜘蛛",
    "Talk show host concludes that antimatter is actually liquified muffins": "脱口秀主持人断定反物质实际上是液化松饼",
    "the maximum attainable temperature of the furnace is 3422 °C?": "炉子可达到的最高温度是 3422 °C？",
    "the Plasma generator's color is yellow?": "等离子发生器的颜色是黄色的？",
    "The price of a mech ciliate has surpassed the price of Bitcoin": "机械纤毛虫的价格已经超过了比特币的价格",
    "the Research Lab is very secretive about its work and is infamous for its security measures?": "研究实验室对其工作非常保密，并因其安全措施而臭名昭著？",
    "unseen spiders are an actually existing non-organic lifeform": "看不见的蜘蛛是一种实际存在的非有机生命形式",
    "A conspiracy theorist claims that nut beetles are programmed to search for a mating bolt": "一位阴谋论者声称坚果甲虫被编程为寻找配对螺栓",
    "A debate on the topic \"Are plasmic frogs actually an organic lifeform?\" has been canceled": "一场关于“浆蛙真的是一种有机生命体吗？”的辩论被取消了",
    "A fellow engineer claims that Pek Monster is an amalgamation of all the known non-organic lifeforms": "一位工程师同事声称，Pek Monster 是所有已知非有机生命形式的融合体",
    "A non-organic isopod race will be held at the canteen right after lunch": "午餐后将在食堂举行非有机等足类动物比赛",
    "A person on the Internet believes that the low-frequency hum of the Plasma generator is a conspiracy": "网上有人认为等离子发生器的低频嗡嗡声是阴谋",
    "a pipe burst in section 13, please put on your radiation shielding suit when passing through. Thank you": "第 13 段管道爆裂，通过时请穿上防辐射服。谢谢",
    "A study reveals that frequent warping is beneficial to one's sex life": "一项研究表明，经常翘曲对性生活有益",
    "An unidentified crawling object (UCO) was spotted devouring what appeared to have been a piece of metal": "发现一个身份不明的爬行物体 (UCO) 吞噬了似乎是一块金属的东西",
    "An unidentified crawling object (UCO) was spotted devouring what appeared to have been another UCO": "发现一个身份不明的爬行物体 (UCO) 吞噬了似乎是另一个 UCO 的东西",
    "duotronic butterflies can change the color of their wings based on their surroundings": "双电子蝴蝶可以根据周围环境改变翅膀的颜色",
    "floor administrators have set up guard posts to catch UFOs that hover over generators": "楼层管理员设置了岗哨，以捕捉盘旋在发电机上方的不明飞行物",
    "floor administrators have set up guard posts to protect the Engineering Den from non-organic isopod gatherings": "楼层管理员设置了岗哨，以保护工程巢穴免受非有机等足类动物的聚集",
    "floor administrators have set up guard posts to ward off plastic flies": "楼层管理员已设立岗哨以抵御塑料苍蝇",
    "Pek Monster is the only non-organic lifeform the existence of which hasn't been documented": "不是怪物 是唯一没有被记录的非有机生命形式",
    "Someone online believes that plastic flies cannot be killed with a plastic flyswatter": "网上有人认为塑料苍蝇拍不能杀死塑料苍蝇",
    "Talk show host insists that non-organic isopods are secretly organic": "脱口秀主持人坚称非有机等足类动物是秘密有机的",
    "Talk show host maintains that the low-frequency hum of the Plasma generator is a conspiracy": "脱口秀主持人坚称等离子发生器的低频嗡嗡声是阴谋",
    "tea is happening": "茶正在发生",
    "The use of mech ciliates as currency begins to outpace crypto": "使用机械纤毛虫作为货币的速度开始超过加密货币",
    "you can sometimes hear the low frequency hum of the Plasma generator as the occasional \"brrrrrrr\"?": "您有时会听到等离子发生器的低频嗡嗡声作为偶尔的“brrrrrrr”？",
    "An unidentified crawling object (UCO) was spotted devouring what appeared to have been a chair": "发现一个身份不明的爬行物体 (UCO) 吞噬了似乎是一把椅子的东西",
    "An unidentified crawling object (UCO) was spotted devouring what appeared to have been an unidentified devoured object (UDO": "一个身份不明的爬行物体 (UCO) 被发现吞噬了似乎是一个身份不明的被吞噬物体 (UDO)",
    "An unidentified crawling object (UCO) was spotted in Mission Control": "在任务控制中心发现了一个身份不明的爬行物体 (UCO)",
    "An unidentified crawling object (UCO) was spotted in Shuttlebay": "在 Shuttlebay 发现了一个不明爬行物体 (UCO)",
    "An unidentified crawling object (UCO) was spotted in the Foundry": "在铸造厂发现了一个不明爬行物体 (UCO)",
    "Be careful when attempting to manually align couplings so as not to be kidnapped by a nanobot tribe": "尝试手动对齐联轴器时要小心，以免被纳米机器人部落绑架",
    "Be especially attentive when attempting to catch a non-organic isopod so as not to be eaten by an unknown organism": "尝试捕捉非有机等足类动物时要特别注意，以免被未知生物吃掉",
    "Be especially attentive when attempting to catch a non-organic isopod so as not to be kidnapped by a nanobot tribe": "尝试捕捉非有机等足类动物时要特别小心，以免被纳米机器人部落绑架",
    "Be extra careful when attempting to debug the low-frequency hum of the Plasma generator so as not to be eaten by an unknown organism": "尝试调试等离子发生器的低频嗡嗡声时要格外小心，以免被未知生物吃掉",
    "Be mindful when attempting to debug the low-frequency hum of the Plasma generator so as not to be eaten by an unknown organism": "尝试调试等离子发生器的低频嗡嗡声时要小心，以免被未知生物吃掉",
    "Be mindful when attempting to debug the low-frequency hum of the Plasma generator so as not to get stuck": "尝试调试等离子发生器的低频嗡嗡声时要小心，以免卡住",
    "cable lizards are considered to be pests because they live in groups and frequently get entangled, blocking passages in the Engineering Den": "电缆蜥蜴被认为是害虫，因为它们群居并经常被缠住，阻塞工程巢穴的通道",
    "duotronic butterflies use tiny magnets to stick to ceilings": "双电子蝴蝶使用微小的磁铁粘在天花板上",
    "EU Parliament considers setting up a workgroup dedicated to studying non-organic isopods as a potential food source": "欧盟议会考虑成立一个工作组，专门研究将非有机等足类动物作为潜在食物来源",
    "EU Parliament was grilled by the press regarding mech ciliates being used as currency throughout the world": "欧盟议会因机械纤毛虫在世界范围内被用作货币而受到媒体质询",
    "EU Parliament was grilled by the press regarding the rights of non-organics to use public charging stations": "欧盟议会被媒体质疑非有机物使用公共充电站的权利",
    "floor administrators have set up guard posts to ward off non-organic isopods": "楼层管理员设置了岗哨以抵御非有机等足类动物",
    "floor administrators have set up guard posts to ward off nut beetles": "楼层管理员已设置岗哨以抵御坚果甲虫",
    "local shops began accepting mech ciliates as currency": "当地商店开始接受机械纤毛虫作为货币",
    "Magnetron's initial probability of becoming armed is 1 in 2000?": "磁控管最初武装的概率是 2000 年的 1？",
    "Mech ciliate trader looses a flask with a billion worth of ciliates": "机械纤毛虫商人丢失了价值十亿纤毛虫的烧瓶",
    "Mech ciliate trader sells ciliates as NFTs": "机械纤毛虫贸易商将纤毛虫作为 NFT 出售",
    "mech ciliates are capable of feeding on antimatter and a cililate colony could devour an antimatter cube in a matter of hours": "机械纤毛虫能够以反物质为食，而纤毛虫群可以在几小时内吞噬掉一个反物质立方体",
    "mech ciliates are usually kept in flasks": "机械纤毛虫通常保存在烧瓶中",
    "nut beetles that get mistaken for regular nuts are able to unscrew themselves and run away in 30% of cases": "被误认为普通坚果的坚果甲虫在 30% 的情况下能够自行拧开并逃跑",
    "organized nanobot tribes generate memes and share them on the Internet": "有组织的纳米机器人部落生成模因并在互联网上分享",
    "Plasma leaks were shown to be a direct consequence of media coverage of the issue": "等离子泄漏被证明是媒体对该问题的报道的直接后果",
    "Poorly written romance novels were shown to be a direct consequence of media coverage of the issue": "写得不好的言情小说被证明是媒体报道这个问题的直接后果",
    "section 2 has been reopened after maintenance": "第 2 节已在维护后重新开放",
    "section 6 is closed for maintenance": "第 6 节已关闭进行维护",
    "section 7 is closed for maintenance": "第 7 节已关闭进行维护",
    "Several items disappeared from the Research Lab. Interns blame each other": "几件物品从研究实验室消失了。实习生互相指责",
    "Several items disappeared from the Research Lab. No donuts were taken": "几件物品从研究实验室消失了。没有吃甜甜圈",
    "Several managers got lost in the Engineering Den last week": "上周几位经理在工程中心迷路了",
    "some corner cafes began accepting mech ciliates as currency": "一些街角咖啡馆开始接受机械纤毛虫作为货币",
    "Someone online alleges that Pek Monster is an amalgamation of all the known non-organic lifeforms": "有人在网上声称 Pek Monster 是所有已知非有机生命形式的融合",
    "Someone online believes that plastic flies are good for economy": "网上有人认为塑料苍蝇对经济有利",
    "Someone online maintains that non-organic isopods are an evolved lifeform": "有人在网上坚持认为非有机等足类动物是一种进化的生命形式",
    "Someone online wonders if they have seen an unseen spider": "网上有人想知道他们是否看到了一只看不见的蜘蛛",
    "Someone online wonders if unseen spiders is a hoax perpetrated by overworked operators": "有人在网上怀疑看不见的蜘蛛是否是过度劳累的操作员的恶作剧",
    "Suspicious odors from one of the containers of the Plasma generator were shown to be a direct consequence of media coverage of the issue": "来自等离子发生器的一个容器的可疑气味被证明是媒体对该问题的报道的直接后果",
    "Talk show host believes that plastic flies cannot be killed with a plastic flyswatter": "脱口秀主持人认为塑料苍蝇不能用塑料苍蝇拍杀死",
    "Talk show host insists that plastic flies are good for economy": "脱口秀主持人坚称塑料苍蝇有利于经济",
    "Talk show host suggests that Pek Monster is an amalgamation of all the known non-organic lifeforms": "脱口秀主持人暗示 Pek Monster 是所有已知非有机生命形式的融合",
    "Talk show host suggests that the low-frequency hum of the Plasma generator is a sign of emerging intelligence": "脱口秀主持人暗示等离子发生器的低频嗡嗡声是新兴智能的标志",
    "Talk show host wonders if plastic flies can be used for a variety of purposes in the home": "脱口秀主持人想知道塑料苍蝇是否可以在家中用于各种用途",
    "the Engineering Den is not a single floor: anything below it is known as the \"jungle\", but is only accessible to Floor Administrators?": "工程巢穴不是一层楼：它下面的任何东西都被称为“丛林”，但只有楼层管理员才能进入？",
    "there are over 70 registered non-organic lifeforms, but only 12 species have established populations": "已登记的非有机生命体有 70 多种，但只有 12 个物种建立了种群",
    "to offset working conditions, some floor administrators have been offered additional incremental game sessions": "为了抵消工作条件，为一些楼层管理员提供了额外的增量游戏会话",
    "to offset working conditions, some floor administrators have been offered additional leave": "为了抵消工作条件，一些楼层管理员获得了额外的假期",
    "tracks of cable lizards were spotted on the wall of the Electric generator": "在发电机的墙上发现了电缆蜥蜴的踪迹",
    "tracks of mutated worms were spotted on the wall of the Nuclear generator": "在核能发电机的墙上发现了变异蠕虫的踪迹",
    "tracks of unseen spiders were spotted on the wall of the Nuclear generator": "在核发电机的墙上发现了看不见的蜘蛛的踪迹",
    "unseen spiders cannot be seen by a human eye, but their tracks can be registered by a clamp meter": "肉眼看不到看不见的蜘蛛，但可以用钳形表记录它们的踪迹",
    "Unseen spiders were shown to be a direct consequence of the second law of thermodynamics": "看不见的蜘蛛被证明是热力学第二定律的直接结果",
    ". You have basic knowledge of how machines work, but you do feel a strong kinship with everything non-organic. You even have a non-organic isopod as a pet, but it's your little secret.": ".你对机器的工作原理有基本的了解，但你确实对所有非有机的事物都有强烈的亲近感。你甚至有一只非有机等足动物作为宠物，但这是你的小秘密。",
    "\"Be the best you can\" - chief engineer": "“尽你所能”——总工程师",
    "\"Do we warp now, man?\" - intern": "“我们现在是不是变形了，伙计？”——实习生",
    "\"Don't complain\" - chief engineer": "“不要抱怨”——总工程师",
    "\"Eat your soup\" - chief engineer": "“吃你的汤”——总工程师",
    "\"Focus on the process, bring me results\" - chief engineer": "“专注过程，给我带来结果”——总工程师",
    "\"foundry\" is the only word that contains the letters \"f\", \"o\", \"u, \"n\", \"d\", \"r\" and \"y\" in exactly that order?": "\"foundry\" 是唯一包含字母 \"f\"、\"o\"、\"u、\"n\"、\"d\"、\"r\" 和 \"y \" 完全按照这个顺序？",
    "\"Higher ups don't know shit\" - chief engineer": "“上级什么都不懂”——总工程师",
    "\"I don't know what you're talking about\" - floor administrator": "“我不知道你在说什么”——楼层管理员",
    "\"I haven't seen anything\" - floor administrator": "“我什么都没看到” - 楼层管理员",
    "\"I heard nothing\" - floor administrator": "“我什么也没听到” - 楼层管理员",
    "\"If you put your mind to it, you can break anything\" - chief engineer": "“只要你下定决心，你可以打破任何东西”——总工程师",
    "\"It's all in your head\" - chief engineer": "“一切都在你的脑海中”——总工程师",
    "\"Lunch?\" - intern": "“午餐？”——实习生",
    "\"Never give up\" - chief engineer": "“永不放弃”——总工程师",
    "\"Nothing ever happens during my shift\" - floor administrator": "“在我轮班期间什么都没有发生” - 楼层管理员",
    "\"Pek Monster is an urban legend for sure\" - floor administrator": "“Pek Monster 无疑是一个都市传奇” - 楼层管理员",
    "\"Shaving is not a requirement\" - chief engineer": "“剃须不是必需品”——总工程师",
    "\"Should we flip this switch?\" - intern": "“我们应该拨动这个开关吗？” - 实习生",
    "\"Stand for what's right\" - chief engineer": "“坚持正确”——总工程师",
    "\"UFOs? Never seen one\" - floor administrator": "“不明飞行物？从未见过” - 楼层管理员",
    "\"What does this button do?\" - intern": "\“这个按钮有什么作用？\” - 实习生",
    "\"Wild, eh?\" - intern": "“狂野，嗯？” - 实习生",
    "\"Wow, what do we do now?\" - intern": "\“哇，我们现在做什么？\” - 实习生",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "January 2022": "2022 年 1 月",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    "Machinery [0.99.1]": "机械师 [0.99.1]",
    'QQ群号': 'QQ群号',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Panel Upgrade ": "面板升级 ",
    "Quantity: ": "数量：",
    "Power": "电源",
    "Debris detected:": "检测到碎片：",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    " warp levels": " 扭曲等级",
    "% Power": "% 电源",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^([\d\.]+)k$/,
    /^⌬([\d\.]+)$/,
    /^⌬([\d\.]+)k$/,
    /^⌬([\d\.]+)M$/,
    /^⌬([\d\.]+)S$/,
    /^⌬([\d\.]+)Q$/,
    /^⌬([\d\.]+)T$/,
    /^⌬([\d\.]+)B$/,
    /^⌬([\d\.]+)k\/⌬([\d\.]+)M$/,
    /^⌬([\d\.]+)M\/⌬([\d\.]+)M$/,
    /^⌬([\d\.]+)M\/⌬([\d\.]+)B$/,
    /^⌬([\d\.]+)B\/⌬([\d\.]+)B$/,
    /^⌬([\d\.]+)k\/⌬([\d\.]+)k$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.,]+) Shuttle$/, '$1 穿梭'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) \/ (.+) elves$/, '成本：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);